import type { Metadata } from "next";
import { Albert_Sans, Montserrat_Alternates } from "next/font/google";
import "./globals.css";
import logo from "../public/printforge-logo 1.png";
import Image from "next/image";
import Link from "next/link";
export const albertSans = Albert_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

export const montserratAlternates = Montserrat_Alternates({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-montserrat-alternates",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${albertSans.className} ${montserratAlternates.variable}`}
      >
        {/* // header */}
        <div className="w-full flex justify-between p-1 items-center">
          {/* // logo */}
          <Link href="/">
            <Image src={logo} alt="logo" />
          </Link>
          {/* // links */}
          <div className="font-medium uppercase ">
            <Link href="/3d-models" className="mr-4">
              3d models
            </Link>
            <Link href="/about" className="mr-4">
              about
            </Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
